server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: securebank-backend

  datasource:
    url: jdbc:mysql://localhost:3306/securebank_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Kolkata
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      pool-name: SecureBankHikariPool
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  data:
    web:
      pageable:
        serialization-mode: via-dto

app:
  jwt:
    # 256-bit Hex Key for HMAC-SHA256 signature
    secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
    expiration-ms: 86400000 # 24 hours
  dormancy:
    inactivity-threshold-days: 90
  cors:
    allowed-origins: "http://localhost:5173,http://localhost:5174,http://localhost:5175,http://localhost:3000,http://127.0.0.1:5173,http://127.0.0.1:5174"

